### PR TITLE
refactor: separate main and sample logic

### PR DESCRIPTION
**Pull request by ImJohnMDaniel**
Change allows for proper separation of "main" logic from the "sample" logic.

This supports the ability for someone to fork/clone the repo and setup the project as an unlocked package without the need to also package the sample code

## Description

General best practice suggests that sample logic should be separate from main/primary logic.  This change achieves that and provides an easy approach to allow someone to package the codebase in an unlocked package.

## How Has This Been Tested?

- Create a scratch org
- Push this code to a scratch org using command `sfdx force:source:push`
- If push is successful, then the test passes

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by ImJohnMDaniel** [comment]
I can see that the validation checks have failed but I am not certain what needs to be changed.  Any guidance on this would be appreciated

**Comment by victorgz** [comment]
Hi @ImJohnMDaniel , thanks for contributing to the project ! 

We've some linting processes to ensure that all the contributions follow some rules & conventions. Some weeks ago, we've included conventional commits in the project, so you need to ensure that your commits and the title of the pull request follow that standard. We're using specifically the [angular convention](https://github.com/angular/angular/blob/22b96b9/CONTRIBUTING.md#-commit-message-guidelines).

For example, you could refactor your PR title to
`refactor: separate main and sample logic in packageDirectories`

And the same things for the two commits that you've pushed

**Comment by ImJohnMDaniel** [comment]
@scolladon and @victorgz -- can you let me know what else needs to be done in order for this PR to approved?  Thanks

**Review by victorgz — APPROVED** [review]

**Comment by victorgz** [comment]
> @scolladon and @victorgz -- can you let me know what else needs to be done in order for this PR to approved? Thanks

Hi @ImJohnMDaniel , thanks for your contribution and sorry for the late reply ! We've been disconnected some with other projets so there has not been a lot of activity here.

I've just approved the changes, however it seems to be a problem with the Github actions coming from a forked repository. There are some secret tokens used by the actions  (whicih obviously are not available in your forked repo) and the actions are executed with your user in the context of our repo. It seems to be a [known issue by Github](https://github.com/actions/first-interaction/issues/10).

I'm gonna try some workarounds and let you know ASAP

**Comment by ImJohnMDaniel** [comment]
@victorgz, Thanks for the update. Let me know if you need anything more from me.  Cheers!

**Comment by victorgz** [comment]
Hi again @ImJohnMDaniel . We've just merged the PR #95 which should fix the problem. However, as we are changing the event triggering the workflow, the current PR won't work even if you just close it and re-open it (because it will be still stuck with the previous context).

Can you please close this Pull Request and create a new one? Sorry for the annoying request, but it seems that there is no other way to go through it 🤦‍♂️

**Pull request merged**
