### PR TITLE
refactor: do not expose base components

### LINKED ISSUE #98: Can we turn off the isExposed flag in the meta?
I want to use the base-components(chart, data, etc..) internally in my salesforce managed package by deploying all the components as part of my package. With the `isExposed` flag turned on I would have to go through a security review from salesforce if I ever plan to delete them in the future. Do you plan to not expose these base components in the future?

### PR DESCRIPTION
**Pull request by victorgz**
## Description

Do not expose the LWCC base components as they won't be available for Lightning Pages. Only the chart builder and sample components will be exposed

## Motivation and Context
resolves #98 

## How Has This Been Tested?

Scratch org

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Review by scolladon — DISMISSED** [review]
LGTM

Just an issue with the CI
It could be fixed here or in the chore one, or in a dedicated PR

**Comment by victorgz** [comment]
> LGTM
> 
> Just an issue with the CI It could be fixed here or in the chore one, or in a dedicated PR

@scolladon Yes, I was thinking about a dedicated PR (I already opened the issue some time ago for that warning). I want to test it to tmake sure that we don't break the deploy to scratch orgs 😅  #97 

The CI error is due to the scratch org daily limit... we'll just have to wait until tomorrow 🤦‍♂️  (I will check if we can have a new devhub with a highest limit)

**Comment by victorgz** [comment]
@scolladon can you re-approve (no rush) when you have the time please ? I had to rebase the branch with master due to some conflicts with the last merge. Thanks ! 🙏

**Review by scolladon — APPROVED** [review]
LGTM !

**Pull request merged**
